### ISSUE TITLE
ConcurrentModificationException of org.eclipse.emf.common.util.AbstractEList

### ISSUE THREAD

**Issue by kris7t** [mde-optimiser/mde_optimiser#49] opened 2019-05-22 20:18 UTC
I am trying to run the development of MDEOptimiser obtained from the p2 update site on Java 11. I also tried Java 8, but with that version, the MDEOptimiser Eclipse plugins failed to load for me. When starting the optimisation either from an Eclipse run configuration, or from the command line with `uk.ac.kcl.inf.mdeoptimiser.interfaces.cli.Run`, I get the following exception:

```
Warning: Nashorn engine is planned to be removed from a future JDK release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.moeaframework.Instrumenter (file:/home/kris/eclipse-2019-03/plugins/org.moeaframework_2.13.0.beta.jar) to field java.util.AbstractCollection.MAX_ARRAY_SIZE
WARNING: Please consider reporting this to the maintainers of org.moeaframework.Instrumenter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:751)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:699)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:685)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:650)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:709)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:698)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:709)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:709)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:709)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:709)
	at org.moeaframework.Instrumenter.instrument(Instrumenter.java:841)
	at org.moeaframework.Executor.runSingleSeed(Executor.java:814)
	at org.moeaframework.Executor.run(Executor.java:748)
	at uk.ac.kcl.inf.mdeoptimiser.libraries.core.optimisation.moea.MoeaOptimisation.runOptimisation(MoeaOptimisation.java:71)
	at uk.ac.kcl.inf.mdeoptimiser.libraries.core.optimisation.moea.MoeaOptimisation.execute(MoeaOptimisation.java:33)
	at uk.ac.kcl.inf.mdeoptimiser.libraries.core.optimisation.OptimisationInterpreter.start(OptimisationInterpreter.java:65)
	at uk.ac.kcl.inf.mdeoptimiser.interfaces.cli.Run.runBatch(Run.java:140)
	at uk.ac.kcl.inf.mdeoptimiser.interfaces.cli.Run.run(Run.java:122)
	at uk.ac.kcl.inf.mdeoptimiser.interfaces.cli.Run.run(Run.java:96)
	at uk.ac.kcl.inf.mdeoptimiser.interfaces.cli.Run.main(Run.java:59)
```

This seems related to https://github.com/MOEAFramework/MOEAFramework/issues/180 , which points at excluding the `org.eclipse` packages from MOEA instrumentation as a possible fix.

After investigating the problem a little more, and jury-rigging a version of `MoeaOptimisation` that excludes `org.eclipse` (along with a custom subclass of `uk.ac.kcl.inf.mdeoptimiser.interfaces.cli.Run` that gets created by the same `MoptStandaloneSetup` injector), I can confirm I no longer get the exception above.

**Comment by alxbrd** [comment] 2019-05-23 00:01
Hi @kris7t,

Thanks for rising this. This is indeed caused by the MOEAFramework. I asked them if they will release an official version with the code that allows us to filter what packages get scanned, but no reply as of yet. I have temporarily created my own build of their master to include that fix and I have a branch that resolves this issue for MDEO.

I am planning to release  a new MDEO version soon, and this fix will be part of it.

Please let me know if you have any other issues.

Thanks.

**Comment by kris7t** [comment] 2019-05-25 04:01
Thanks for the fix!
I find it a bit strange that you needed to build MOEAFramework yourself -- after installing the MDEOptimiser develop version from the p2 repo in a new Eclipse 2019-03 instance, I have `org.moeaframework` version `2.13.0.beta`, which has a `Instrumenter` with an `addExcludedPackage` method, as mentioned in the linked bug report.
By the way, this is the workaround that I am currently using for my experiments: https://gist.github.com/kris7t/0160c11dc0f5cce012359b128f266315 Basically, I can just `new MoptStandaloneSetup().createInjectorAndDoEMFRegistration().getInstance(ExcludedRun).run(PROJECT_PATH, MOPT_PATH)` (and make sure never to create another Injector for the mopt language).

**Comment by alxbrd** [comment] 2019-05-28 14:15
MOEAFramework `2.13.0.beta` is the personal build I was talking about. Version `2.12`, which is available on Maven Central, does not have that package exclude code merged.

I added a fix and will merge it in develop after the checks pass.

Thanks for rising this.

**Closed** 2019-05-29 16:08 UTC

**Comment by kris7t** [comment] 2019-06-09 19:14
Thanks! (And sorry for the late reply!)
After the update, I don't get this exception any more.
